# Generated by Django 3.2.2 on 2021-05-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='sub_url',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
