# Generated by Django 3.2.2 on 2021-06-05 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_sites_sub_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='analytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=100)),
                ('ip', models.URLField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(max_length=10, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.sites')),
            ],
        ),
    ]
