# Generated by Django 3.2.2 on 2021-06-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_analytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='device',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='ip',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
